### ISSUE TITLE
Fix Rocket Turret

### ISSUE THREAD

**Issue by ghost** [ChaosInitiative/Portal-2-Community-Edition#26]
Fix Rocket Turret's bug where rockets spawn with a speed of 0 (and finish Tripwire Mode?).

**Comment by Luke18033** [comment]
Was about to open an issue about this when I saw this one. Here are the specific issues that I've found:
- Getting a rocket turret to actually target the player is a pain. You need to fire a `SetTarget` input to it every time before it's turned on, and it can only target one specific player in Co-op.
	- Maybe change this to be based on AI relationships, like it is with normal turrets.
- Rockets are spawned with a speed of 0, and usually don't deal any damage
- Some people have issues with invisible rockets, I can't reproduce this though.
- There is no targeting laser

**Comment by Nuclear-Adakam** [comment]
small details for this that i think would be good is to remove the weird blue lens flare, and the activation beep which overextends the delay before firing

**Comment by Luke18033** [comment]
Honestly most of what needs to be done is just reverting it to how it worked in P1. Though there are some improvements that could be made, like switching it to using AI relationships as I suggested.

**Comment by Luke18033** [comment]
Also:
- Setting the turret to tripwire mode shouldn't automatically get rid of the fire delay. Maybe make it toggleable with a keyvalue.
- The turret can act kind of buggy if turned off while in the "locked on" state (yellow eye). When turned back on it will not visually enter this state the first time.
- There's an inactive texture for the rocket turret, but the skin isn't present on the model and the entity doesn't try to switch to it. Add support for this.
- @Byzarru made some custom rocket turret textures that better match the design of the P2 turrets, which someone suggested including in P2:CE.

**Comment by Luke18033** [comment]
I merged all the bugs/suggestions into my original comment, there are some new things on there as well.

**Comment by FrozenDragon0** [comment]
We should also have an option to switch what explosion sound is used. I just feel that the HL2/Portal 1 explosion sound suits the rocket turret compared to P2's one.

**Comment by Luke18033** [comment]
That can already be done by replacing the soundscript.

**Comment by BlightedLight** [comment]
I partially fixed the rocket turret, allowing it to actually shoot. I never pushed the fix as I never finished fixing all the other bugs related to it, I will look into it again soon.

**Comment by CitadelCore** [comment]
The basics of this have been fixed, I'll leave the other small issues for another time.
